### ISSUE TITLE
Not loading in ModOrganizer

### ISSUE THREAD

**Issue by fucnknown** [ModOrganizer2/modorganizer-game_skyrimVR#1]
Creating report here because https://github.com/ThomasBrixLarsen/modorganizer-game_skyrimVR/ does not have "issues" section open.    

- Downloaded MO2 standalone version from [Nexus](https://www.nexusmods.com/skyrimspecialedition/mods/6194) (Also tried with releases from [Github](https://github.com/Modorganizer2/modorganizer/releases))
- Left plugin in plugins folder
- On New Instance, SkyrimVR does not appear as an option

You can see in  **mo_interface.log** ([https://pastebin.com/SzrDLe06](https://pastebin.com/SzrDLe06)) that it loads the plugin correctly.
I don't see any mention of it in **ModOrganizer.ini** ([https://pastebin.com/zgdisAHK](https://pastebin.com/zgdisAHK)) however. (I'm not familiar with MO2 enough to know if it should)

PS: You will notice references to SkyrimSpecialEdition, I tried using that option in instance, since the plugin is a fork of the SSE one, expecting that once targeted to the correct exe it would work. However it edited/modified the plugins.ini in SSE folder (<user>/Appdata/Local/SkyrimSpecialEdition) instead of SkyrimVR.

**Comment by Silarn** [comment]
I'm guessing this is because of the common misconception that the first list of options is actually a game selection dialog. This is not true, you're simply setting the name of that instance. (The directory name holding the settings and files.) Only after this are you asked to select an available game directory.

The latest version of the UI makes this distinction more clear.

That being said, I'm unsure if builds of game plugins created recently are going to work properly with older builds of MO2. The one bundled with the latest dev builds (and imminent release) will definitely include it.
